export * from './translations/types';

export interface Settings {
  SPONSORED: boolean,
  NF_TABLIST_STORIES_REELS_ROOMS: boolean,
  NF_STORIES: boolean,
  NF_SURVEY: boolean,
  NF_PEOPLE_YOU_MAY_KNOW: boolean,
  NF_PAID_PARTNERSHIP: boolean,
  NF_SPONSORED_PAID: boolean,
  NF_SUGGESTIONS: boolean,
  NF_FOLLOW: boolean,
  NF_PARTICIPATE: boolean,
  NF_REELS_SHORT_VIDEOS: boolean,
  NF_SHORT_REEL_VIDEO: boolean,
  NF_EVENTS_YOU_MAY_LIKE: boolean,
  NF_ANIMATED_GIFS_POSTS: boolean,
  NF_ANIMATED_GIFS_PAUSE: boolean,
  NF_SHARES: boolean,
  NF_AUTO_REDIR_TO_MOST_RECENT: boolean,
  NF_LIKES_MAXIMUM: boolean,
  GF_PAID_PARTNERSHIP: boolean,
  GF_SUGGESTIONS: boolean,
  GF_SHORT_REEL_VIDEO: boolean,
  GF_ANIMATED_GIFS_POSTS: boolean,
  GF_ANIMATED_GIFS_PAUSE: boolean,
  GF_SHARES: boolean,
  VF_LIVE: boolean,
  VF_INSTAGRAM: boolean,
  VF_DUPLICATE_VIDEOS: boolean,
  VF_ANIMATED_GIFS_PAUSE: boolean,
  PP_ANIMATED_GIFS_POSTS: boolean,
  PP_ANIMATED_GIFS_PAUSE: boolean,
  NF_BLOCKED_FEED: ['0' | '1', '0' | '1', '0' | '1'],
  GF_BLOCKED_FEED: ['0' | '1', '0' | '1', '0' | '1'],
  VF_BLOCKED_FEED: ['0' | '1', '0' | '1', '0' | '1'],
  MP_BLOCKED_FEED: ['0' | '1', '0' | '1', '0' | '1'],
  PP_BLOCKED_FEED: ['0' | '1', '0' | '1', '0' | '1'],
  OTHER_INFO_BOX_CORONAVIRUS: boolean,
  OTHER_INFO_BOX_CLIMATE_SCIENCE: boolean,
  OTHER_INFO_BOX_SUBSCRIBE: boolean,
  REELS_CONTROLS: boolean,
  REELS_DISABLE_LOOPING: boolean,
  NF_BLOCKED_ENABLED: boolean,
  GF_BLOCKED_ENABLED: boolean,
  VF_BLOCKED_ENABLED: boolean,
  MP_BLOCKED_ENABLED: boolean,
  PP_BLOCKED_ENABLED: boolean,
  NF_BLOCKED_RE: boolean,
  GF_BLOCKED_RE: boolean,
  VF_BLOCKED_RE: boolean,
  MP_BLOCKED_RE: boolean,
  PP_BLOCKED_RE: boolean,
  DLG_VERBOSITY: '0' | '1',
  VERBOSITY_DEBUG: boolean,
  VERBOSITY_MESSAGE_BG_COLOUR: string,
  CMF_BTN_OPTION: '0' | '1',
  CMF_DIALOG_OPTION: '0' | '1',
  CMF_BORDER_COLOUR: string,
}