#!/usr/bin/env bun

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { minify } from 'terser';
import { generateUserscriptHeader } from './utils/userscript.js';
import { transformStyleObjects } from './utils/transform-styles.js';
import packageJson from '../package.json';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

const SRC_FILE = join(projectRoot, 'src', 'index.js');
const OUTPUT_DIR = join(projectRoot, 'dist');
const OUTPUT_FILE = join(OUTPUT_DIR, 'fb-clean-my-feeds.user.js');
const OUTPUT_META_FILE = join(OUTPUT_DIR, 'fb-clean-my-feeds.meta.js');

if (!existsSync(SRC_FILE)) {
  console.error(`Source entrypoint not found: ${SRC_FILE}`);
  process.exit(1);
}

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

function cleanVersion(versionStr) {
  if (!versionStr || typeof versionStr !== 'string') return '';
  return versionStr
    .trim()
    .replace(/^refs\/tags\//i, '')
    .replace(/^v/i, '')
    .trim();
}

function resolveTargetVersion(defaultVersion = '') {
  // 1. CLI argument (--version <ver>, -v <ver>, or --version=<ver>)
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--version' || arg === '-v') {
      if (argv[i + 1]) {
        return cleanVersion(argv[i + 1]);
      }
    }
    if (arg.startsWith('--version=')) {
      return cleanVersion(arg.slice(10));
    }
  }

  // 2. Explicit environment variables
  if (process.env.USERSCRIPT_VERSION) {
    return cleanVersion(process.env.USERSCRIPT_VERSION);
  }
  if (process.env.BUILD_VERSION) {
    return cleanVersion(process.env.BUILD_VERSION);
  }

  // 3. GitHub Actions tag environment
  if (process.env.GITHUB_REF_TYPE === 'tag' && process.env.GITHUB_REF_NAME) {
    return cleanVersion(process.env.GITHUB_REF_NAME);
  }
  if (process.env.GITHUB_REF && process.env.GITHUB_REF.startsWith('refs/tags/')) {
    return cleanVersion(process.env.GITHUB_REF);
  }

  // 4. Git exact tag on current commit
  try {
    const proc = Bun.spawnSync(['git', 'describe', '--tags', '--exact-match'], {
      stderr: 'pipe',
    });
    if (proc.exitCode === 0) {
      const tag = proc.stdout.toString().trim();
      if (tag) return cleanVersion(tag);
    }
  } catch {
    // Git command failed or untagged
  }

  // 5. Default fallback
  return cleanVersion(defaultVersion);
}

const targetVersion = resolveTargetVersion(packageJson.version);
console.log(`Building userscript with Bun (target version: ${targetVersion})...`);
const startTime = performance.now();

const styleTransformerPlugin = {
  name: 'style-object-to-css',
  setup(build) {
    build.onLoad({ filter: /src\/styles\/.*\.js$/ }, async (args) => {
      const source = readFileSync(args.path, 'utf-8');
      const transformed = transformStyleObjects(source);
      return {
        contents: transformed,
        loader: 'js',
      };
    });
  },
};

try {
  const result = await Bun.build({
    entrypoints: [SRC_FILE],
    outdir: OUTPUT_DIR,
    naming: { entry: 'fb-clean-my-feeds.user.js' },
    target: 'browser',
    format: 'iife',
    minify: false,
    plugins: [styleTransformerPlugin],
  });

  if (!result.success) {
    console.error('Build failed with errors:');
    for (const message of result.logs) {
      console.error(message);
    }
    process.exit(1);
  }

  let builtContent = readFileSync(OUTPUT_FILE, 'utf-8');

  // Ensure entrypoint __commonJS wrapper is invoked inside IIFE if generated by Bun
  const commonJsMatch = builtContent.match(/var\s+(require_[a-zA-Z0-9_$]+)\s*=\s*__commonJS/);
  if (commonJsMatch) {
    const fnName = commonJsMatch[1];
    // Find all occurrences: if only defined but not invoked
    const occurrences = builtContent.match(new RegExp(`\\b${fnName}\\b`, 'g')) || [];
    if (occurrences.length <= 1 || !builtContent.slice(-200).includes(`${fnName}()`)) {
      builtContent = builtContent.replace(/\n\}\)\(\);\s*$/, `\n  ${fnName}();\n})();\n`);
    }
  }

  // Also replace any unexpected top-level "export default require_...();"
  builtContent = builtContent.replace(/export\s+default\s+(require_[a-zA-Z0-9_$]+)\(\);?/g, '$1();');

  // Strip all comments (including Bun's auto-inserted module-path comments)
  // without mangling names or compressing logic.
  const minified = await minify(builtContent, {
    compress: false,
    mangle: false,
    format: {
      comments: false,
      beautify: true,
      indent_level: 2,
    },
  });

  builtContent = minified.code;

  // Prepend authoritative header using packageJson.userscript with resolved targetVersion
  const metadataConfig = {
    ...packageJson.userscript,
    version: targetVersion,
  };
  const header = generateUserscriptHeader(metadataConfig, targetVersion);
  const finalContent = header + '\n' + builtContent;

  writeFileSync(OUTPUT_FILE, finalContent, 'utf-8');
  writeFileSync(OUTPUT_META_FILE, header, 'utf-8');

  const duration = (performance.now() - startTime).toFixed(1);
  const sizeKb = (Buffer.byteLength(finalContent, 'utf-8') / 1024).toFixed(2);

  console.log(`Userscript built successfully in ${duration}ms: ${OUTPUT_FILE}`);
  console.log(`File size: ${sizeKb} KB`);
} catch (error) {
  console.error('Build failed with exception:', error);
  process.exit(1);
}
