#!/usr/bin/env bun

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { generateUserscriptHeader } from './utils/userscript.js';
import packageJson from '../package.json';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

const SRC_FILE = join(projectRoot, 'src', 'index.js');
const OUTPUT_DIR = join(projectRoot, 'dist');
const OUTPUT_FILE = join(OUTPUT_DIR, 'fb-clean-my-feeds.user.js');

if (!existsSync(SRC_FILE)) {
  console.error(`Source entrypoint not found: ${SRC_FILE}`);
  process.exit(1);
}

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('Building userscript with Bun (Vanilla JavaScript)...');
const startTime = performance.now();

try {
  const result = await Bun.build({
    entrypoints: [SRC_FILE],
    outdir: OUTPUT_DIR,
    naming: { entry: 'fb-clean-my-feeds.user.js' },
    target: 'browser',
    format: 'iife',
    minify: false,
  });

  if (!result.success) {
    console.error('Build failed with errors:');
    for (const message of result.logs) {
      console.error(message);
    }
    process.exit(1);
  }

  let builtContent = readFileSync(OUTPUT_FILE, 'utf-8');

  // Strip existing userscript header if present in bundled content to prevent duplicates
  builtContent = builtContent.replace(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/m, '');

  // Ensure entrypoint __commonJS wrapper is invoked inside IIFE if generated by Bun
  const commonJsMatch = builtContent.match(/var\s+(require_[a-zA-Z0-9_$]+)\s*=\s*__commonJS/);
  if (commonJsMatch) {
    const fnName = commonJsMatch[1];
    // Check if the function call fnName() is already present
    const callPattern = new RegExp(`\\b${fnName}\\s*\\(`);
    // Find all occurrences: if only defined but not invoked
    const occurrences = builtContent.match(new RegExp(`\\b${fnName}\\b`, 'g')) || [];
    if (occurrences.length <= 1 || !builtContent.slice(-200).includes(`${fnName}()`)) {
      builtContent = builtContent.replace(/\n\}\)\(\);\s*$/, `\n  ${fnName}();\n})();\n`);
    }
  }

  // Also replace any unexpected top-level "export default require_...();"
  builtContent = builtContent.replace(/export\s+default\s+(require_[a-zA-Z0-9_$]+)\(\);?/g, '$1();');

  // Prepend authoritative header using packageJson.userscript with packageJson.version reference
  const header = generateUserscriptHeader(packageJson.userscript, packageJson.version);
  const finalContent = header + '\n' + builtContent;

  writeFileSync(OUTPUT_FILE, finalContent, 'utf-8');

  const duration = (performance.now() - startTime).toFixed(1);
  const sizeKb = (Buffer.byteLength(finalContent, 'utf-8') / 1024).toFixed(2);

  console.log(`Userscript built successfully in ${duration}ms: ${OUTPUT_FILE}`);
  console.log(`File size: ${sizeKb} KB`);
} catch (error) {
  console.error('Build failed with exception:', error);
  process.exit(1);
}
